version: "3.9"

x-shared-volumes: &shared-volumes
  volumes:
    - './star_wars:/app'

services:
  db:
    image: postgres
    container_name: db
    env_file: .env.local # * save private configs
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - '5435:5432'
    restart:
      unless-stopped
  web:
    build:
      context: .
    env_file: .env.local 
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    <<: *shared-volumes