# Generated by Django 4.2 on 2023-07-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Planet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Planet Name")),
                ("diameter", models.CharField(max_length=15, verbose_name="Diameter")),
                ("gravity", models.IntegerField(verbose_name="Gravity")),
                ("population", models.IntegerField(verbose_name="Population")),
                ("climate", models.CharField(max_length=30, verbose_name="Climate")),
                (
                    "img_url",
                    models.URLField(
                        max_length=500, null=True, verbose_name="Image URL"
                    ),
                ),
            ],
            options={
                "verbose_name": "Planet",
                "verbose_name_plural": "Planets",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                ("opening_crawl", models.TextField(verbose_name="Opening paragraph")),
                ("directors", models.JSONField(default=list, verbose_name="Directors")),
                ("producers", models.JSONField(default=list, verbose_name="Producers")),
                ("release_date", models.DateField(verbose_name="Release date")),
                (
                    "img_url",
                    models.URLField(
                        max_length=500, null=True, verbose_name="Image URL"
                    ),
                ),
                (
                    "planets",
                    models.ManyToManyField(related_name="films", to="API.planet"),
                ),
            ],
            options={
                "verbose_name": "Film",
                "verbose_name_plural": "Films",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=7,
                        verbose_name="Gender",
                    ),
                ),
                ("age", models.IntegerField(verbose_name="Age")),
                (
                    "skin_color",
                    models.CharField(max_length=30, verbose_name="Skin color"),
                ),
                (
                    "eye_color",
                    models.CharField(max_length=30, verbose_name="Eye color"),
                ),
                ("height", models.IntegerField(verbose_name="Height")),
                ("mass", models.IntegerField(verbose_name="Mass")),
                (
                    "img_url",
                    models.URLField(
                        max_length=500, null=True, verbose_name="Image URL"
                    ),
                ),
                (
                    "films",
                    models.ManyToManyField(related_name="characters", to="API.film"),
                ),
            ],
            options={
                "verbose_name": "Character",
                "verbose_name_plural": "Characters",
                "ordering": ("id",),
            },
        ),
    ]
