# Generated by Django 4.2 on 2023-07-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="film",
            name="characters",
            field=models.ManyToManyField(related_name="films", to="API.character"),
        ),
        migrations.AlterField(
            model_name="film",
            name="planets",
            field=models.ManyToManyField(related_name="films", to="API.planet"),
        ),
    ]
