# Generated by Django 4.2 on 2023-07-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0002_film_characters_alter_film_planets"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="img_url",
            field=models.URLField(max_length=500, null=True, verbose_name="Image URL"),
        ),
        migrations.AddField(
            model_name="film",
            name="img_url",
            field=models.URLField(max_length=500, null=True, verbose_name="Image URL"),
        ),
        migrations.AddField(
            model_name="planet",
            name="img_url",
            field=models.URLField(max_length=500, null=True, verbose_name="Image URL"),
        ),
    ]
